### ISSUE TITLE
GitHub Actions for Releases

### ISSUE THREAD

**Issue by braydonk** [google/yamlfmt#10]
I did the v0.1.0 release manually, but it would be much preferred if the releases could be automated through GitHub Actions using the existing `goreleaser` configuration.

**Comment by longkai** [comment]
I've done it via [GitHub Actions](https://github.com/longkai/yamlfmt/actions/runs/3180081620/jobs/5183250655)(use goreleaser to build the vscode extension bundled binary). Each time creating a release in Github webpage, it will auto build and upload the artifacts via [this action](https://github.com/softprops/action-gh-release).

How do you think about this or do it with goreleaser all the way?
