### ISSUE TITLE
Bug: 'retain_line_breaks' on folded bleeds '#magic___^_^___line'

### ISSUE THREAD

**Issue by woodgiraffe** [google/yamlfmt#109]
Version: `latest`

To reproduce:

`printf "a: >-\n  b\n\n# c\n" | yamlfmt -formatter "retain_line_breaks=true" -`

Actual Input:
```yaml
a: >-
  b

# c
```

Actual Output:
```yaml
a: >-
  b #magic___^_^___line
# c
```

Expected Output:
```yaml
a: >-
  b

# c
```

**Comment by braydonk** [comment]
Thanks for making an issue! This looks similar to #86 so I'll keep tracking the work there. Keep an eye out there for updates. I'll close this issue for now.

**Comment by woodgiraffe** [comment]
Gotcha. Thanks for your work on `yamlfmt`! It's very useful!
