### ISSUE TITLE
0.10.0 release?

### ISSUE THREAD

**Issue by campbel** [google/yamlfmt#133]
Could we get a 0.10.0 (or 0.9.1) release to ship this fix? https://github.com/google/yamlfmt/commit/908b19015fc4bffc54b1d554b83fe6c1c93b20ee

Without this fix excludes essentially don't work which is fairly annoying.

Thanks!

**Comment by braydonk** [comment]
Thanks for opening an issue, I'll get that out in a bit. I held off on releasing cause there was one more feature I was planning, but then work and summer stuff was too busy to do it. Sorry for the delay.

**Comment by braydonk** [comment]
v0.10.0 is out!
