### ISSUE TITLE
Unexpected reformatting of block scalar?

### ISSUE THREAD

**Issue by andoks** [google/yamlfmt#136]
With the following example, yamlfmt rewrites the value of "something" to not use the block scalar syntax when specifying `scan_folded_as_literal=true` (` yamlfmt -formatter scan_folded_as_literal=true test.yml`), if there is a space character after any of the lines in the scalar. I am not an expert in YAML though, so this might be intentional, but it took me by surprise.

```yaml
something: >
  {
   "foo": "bar", 
  }
```

**Comment by braydonk** [comment]
Going to close this issue since I'll continue tracking work in #86; if you can +1 that bug as well it helps me keep track. Thanks!
