### ISSUE TITLE
Feature Request: Optional exclude content from .gitignore

### ISSUE THREAD

**Issue by otteydw** [google/yamlfmt#140]
Since we store a bunch of files and directories to exclude in a local .gitignore file, it would help if this tool excluded that list of files too -- or at least allowed us to enter a list of excludes from a file (which could be the .gitignore file).

It would save from repeating file content between our .gitignore and our .yamlfmt file.

**Comment by braydonk** [comment]
Hi @otteydw thank you for the feature request! I am not sure how missed this when you first opened it. I've opened a PR to add this feature and it will be in v0.11.0 that I plan to release soon.
