### ISSUE TITLE
Support finding a local yamlfmt config file named `.yamlfmt.yaml`

### ISSUE THREAD

**Issue by nogweii** [google/yamlfmt#160]
Add an additional filename that can be found (or maybe two, with both variations of the extension). It'd be nice if `~/code/foobar/.yamlfmt.yaml` was loaded, as that would means editors will easily detect the file type.

**Comment by braydonk** [comment]
Hi @nogweii,

v0.11.0 added support for calling the file `yamlfmt.yml` or `yamlfmt.yaml`. I opened a PR so those can be hidden as well.
