### ISSUE TITLE
yamlfmt does not retain indent in `>-`(Line Folding)

### ISSUE THREAD

**Issue by kachick** [google/yamlfmt#182]
For actual example from [.goreleaser.yml](https://github.com/google/yamlfmt/blob/v0.12.1/.goreleaser.yaml#L28-L36) in this repository

With yamlfmt `0.12.1`

```bash
cat <<'EOF' | yamlfmt -in
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{- .Arch }}{{- end }}
      {{- if .Arm }}v{{- .Arm }}{{- end }}
EOF
```

It outputs 

```plaintext
archives:
  - name_template: >-
      {{ .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{- .Arch }}{{- end }} {{- if .Arm }}v{{- .Arm }}{{- end }}
```

From [yaml spec](https://yaml.org/spec/1.2.2/#line-folding)

>Line folding allows long lines to be broken for readability, while retaining the semantics of the original long line. If a line break is followed by an empty line, it is trimmed; the first line break is discarded and the rest are retained as content.

If this behavior is correct, I think we don't need any `>-` syntax in YAML.

**Comment by braydonk** [comment]
Hi @kachick do you have `scan_folded_as_literal` set here? I added that setting to deal with this problem.

**Comment by kachick** [comment]
Oh... sorry, I didn't understand this flag 🙇‍♂️

Perfectly resolved!

(But I dont't know when `scan_folded_as_literal: false` maybe  useful... 🤔)

**Comment by braydonk** [comment]
No problem, I understand it's not very well named. I was really struggling to come up with a name for it. Realistically I think it should default to on. I have a general rule that when any feature is a result of me changing/adding something to my fork of the yaml library, I don't default it to on in case there is a niche case where it broke. I could probably come up with a better solution for leaving things default off at first and having a schedule for defaulting them on after not receiving issues about it for long enough. I'll think about a plan for this going forward!
