### ISSUE TITLE
Json schema is not valid

### ISSUE THREAD

**Issue by serpro69** [google/yamlfmt#201]
Tried to use the schema via https://github.com/redhat-developer/yaml-language-server and getting the following error:

![image](https://github.com/user-attachments/assets/37b92056-488c-4752-a238-3dc605f03699)

**Comment by thiagowfx** [comment]
In the future, please paste the original file as text.

Thanks for the heads-up, I sent a PR that should fix it.

PS. In your example, you probably want:

```
formatter:
  indent: 2
```

**Comment by serpro69** [comment]
Hi @thiagowfx ,
First, thanks for the fix :) I can confirm it's working fine now.

Yes, the `formatter` key was missing in the screenshot, I've fixed that, but since that didn't affect the root cause of the issue - I didn't think it was relevant to update the description.
I also didn't consider including the config as text since it didn't include anything apart from the reference to the schema file in this repo.

Cheers
