### ISSUE TITLE
Cosign Files Not Present in Release

### ISSUE THREAD

**Issue by thkawcha** [google/yamlfmt#211]
Following the Download & Install from Release artifacts docs: https://github.com/google/yamlfmt/blob/main/README.md#verifying-release-artifacts

There is a step to validate the release artifacts with cosign:
```bash
curl -sfLO https://github.com/google/yamlfmt/releases/download/vA.B.C/checksums.txt
curl -sfLO https://github.com/google/yamlfmt/releases/download/vA.B.C/checksums.txt.pem
curl -sfLO https://github.com/google/yamlfmt/releases/download/vA.B.C/checksums.txt.sig
```

These files are not present in the release. Only the `checksums.txt` file is present - https://github.com/google/yamlfmt/releases/tag/v0.13.0

It looks like this is the case for other recent releases as well.

**Comment by braydonk** [comment]
Hi @thkawcha,

That cosign support was only added recently and will start working from the next release onward. I added a clarifying note to the README. Thanks for catching that.
