### ISSUE TITLE
0.13.0 on Windows forces yaml file to end lines with CRLF

### ISSUE THREAD

**Issue by msen-aiq** [google/yamlfmt#214]
in 0.13.0 binary for Windows x86_64, even if with `line_ending: lf` specified in `.yamlfmt` (or manually specifying config file), yaml files are replaced with CRLF line endings.

This is not happeing in 0.12.1.

**Comment by braydonk** [comment]
Hi @msen-aiq thanks for opening an issue.

I was able to reproduce this issue with the following config:
```yaml
formatter:
  line_ending: lf
```
That does not apply. I know what I did wrong and am working on a fix.

The workaround is to specify the `line_ending` setting at the top level of the file like so:
```yaml
line_ending: lf
```
When I did this it seems to have worked as expected. Sorry for the inconvenience I'll try to get this resolved soon.
