### ISSUE TITLE
%YAML:1.0 give error

### ISSUE THREAD

**Issue by niroosh1997** [google/yamlfmt#215]
when in the start of the file there is %YAML:1.0
then tells that yaml including non alphabetical character and not linting file.

**Comment by braydonk** [comment]
Hi @niroosh1997 thanks for opening an issue.

It looks like the underlying yaml library does not support directives. I could potentially add a hotfix where yamlfmt purposely strips directives and puts them back in after the document similar to other features I've added. Worth noting though, the YAML 1.0 spec is similarly not supported by the YAML parser (see [that library's README](https://github.com/go-yaml/yaml?tab=readme-ov-file#compatibility)).

**Comment by niroosh1997** [comment]
Seems like great hotfix for my purposes!

I did it manually and it works great so would love this hotix


Thanks Nir

**Comment by braydonk** [comment]
I will try and get something added in soon, along with documentation stating that directives are ignored and will have no affect on parsing.
