### ISSUE TITLE
Failure if folders with `.yml` and `.yaml` in the name exist

### ISSUE THREAD

**Issue by alethenorio** [google/yamlfmt#57]
When running the tool, it will fail if there is a folder with `.yml` or `.yaml` in the name.

Maybe we should we skip folders when attempting for format yaml files?

**Comment by braydonk** [comment]
Thanks for making an issue! Never considered this use case. Should be a simple fix. I'll probably be able to get to it this week, but on the off chance there's anyone interested in contributing I'll mark it as a good first issue.
