### ISSUE TITLE
feat: use ${XDG_CONFIG_HOME}/yamlfmt/config.yml values as fallback

### ISSUE THREAD

**Issue by kyoh86** [google/yamlfmt#67]
I'm using some formatters like `black`, `stylua`,.
I can use 'global' configurations for them, stored in a home-directory as fallback, like below.

- `~/.config`
    - `black/pyproject.toml`
    - `stylua/styula.toml`

I can manage them in one repository (it holds a part of `~/.config`) conveniently.
Would you consider supporting such a global configuration file?

**Comment by braydonk** [comment]
Thanks for making an issue! This seems like a great feature, I'll implement it in the next release.

**Comment by kyoh86** [comment]
Thank you for your quick response!!!!!!
