### ISSUE TITLE
Please consider requiring `yamlfmt .` or similar before recursively rewriting *.yaml

### ISSUE THREAD

**Issue by amenonsen** [google/yamlfmt#71]
Otherwise it's a little too easy to run it in the wrong directory and not even know what's changed.

**Comment by braydonk** [comment]
Thanks for making an issue!

Yeah, it looks like most other similar formatting tools also do this. I'll join the pack. Sorta sucks that it's a breaking change but we're still in 0.x land anything can happen :laughing:
