### ISSUE TITLE
There is a pesky hyphen that trips others downstream

### ISSUE THREAD

**Issue by paveloom** [google/yamlfmt#80]
Starting with `v0.7.0`, `yamlfmt` prints an extra hyphen when called with the `-` argument (read from `stdin`, output to `stdout`):

![image](https://user-images.githubusercontent.com/49961859/211208848-84976ca8-84da-4f3d-b39b-bbf352d0cdf6.png)

Is that intentional or is that a regression?

Unfortunately, this leads to things breaking downstream. See https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1331, for an example.

**Comment by braydonk** [comment]
Thanks for making an issue. This is almost certainly a regression, I'll try and get a patch out.

**Comment by braydonk** [comment]
Oh my god I left a `fmt.Println` in, I have no idea how I let that slip! Patch will be out in a couple hours when I can get back to a computer.

**Comment by braydonk** [comment]
I will make a patch release for this shortly.

**Comment by braydonk** [comment]
Released in v0.7.1. Sorry for the inconvenience!
