### ISSUE TITLE
Provide filename instead of diff to stdout

### ISSUE THREAD

**Issue by mnil** [google/yamlfmt#85]
When integrating this into our repo we run a wrapped yamlfmt as part of a suite of misc checks. In our case the diff piped to stdout can be quite large and not very interesting in my opinion, the more helpful approach in our case would be to just provide the path of the files with incorrect formatting. Would it be possible to add this behavior under some flag?

**Comment by braydonk** [comment]
I didn't consider this use case, seems like a good feature. I will try and get something for this in the next release.

**Comment by braydonk** [comment]
@mnil I merged #90 which adds a `-quiet` flag. I am just working on one more thing before releasing 0.8.0, but you can pull `github.com/google/yamlfmt@main` to try the feature early. Thank you for the feature idea!

**Comment by mnil** [comment]
thanks, I will try it out!
