### ISSUE TITLE
Add option to remove indentation on arrays 

### ISSUE THREAD

**Issue by pmialon** [google/yamlfmt#87]
Yaml support indented or not array.
```yaml
array:
  - a
  - b
```

```yaml
array:
- a
- b
```

 It would be great if the basic formater had an option to remove spaces before hyphens.

**Comment by braydonk** [comment]
Thanks for making an issue!

I should be able to do this in the next release.

**Comment by braydonk** [comment]
Hi @seh, yes it's definitely valid yaml. The library simply doesn't expose an option to change to the unindented style. I have seen there's an example of someone else adding this option in their own fork of the same library, I can likely use that as inspiration to add the same thing. After that I will add an option in yamlfmt for it.

**Comment by pmialon** [comment]
Thanks @braydonk !
yamlfmt is now perfect for me.
