### ISSUE TITLE
Option to specify format options directly through CLI args

### ISSUE THREAD

**Issue by UtkarshVerma** [google/yamlfmt#88]
I use `yamlfmt` in my NVIM setup. I want to avoid creating a `config.yaml` and instead configure the formatting behaviour through the CLI args instead. Most other formatters already support this.

For example, to set the `max_line_length`, I just wish to do the following:
```sh
yamlfmt --max-line-length=80 in.yaml
```

**Comment by UtkarshVerma** [comment]
`yamllint` has the `-d` flag which would also seem apt for my use case.

**Comment by braydonk** [comment]
Thanks for making an issue!

This would be harder than it sounds. I could do it, but I would need to redesign how the tool actually discovers its config.

As a quicker thing, the tool does support using a `.yamlfmt` file in the system-wide config directory. It's not quite as convenient for a neovim config as cli flags would be, but it would be easier than having to make a `.yamlfmt` for every directory.

**Comment by braydonk** [comment]
I think I've come up with a sane way to do this now, it will be in the next release.

**Comment by braydonk** [comment]
This is merged! You can try it out by installing from main: `go install github.com/google/yamlfmt/cmd/yamlfmt@main` or wait til v0.9.0 release which I'm aiming to do next week.

**Comment by UtkarshVerma** [comment]
Thanks a lot!
